=== Odie8683/one-rom/rust/studio/manifest/app-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Manifest",
  "description": "One ROM Studio application manifest",
  "type": "object",
  "properties": {
    "firmware_build_compatibility": {
      "description": "Firmware compatibility information.  Represents maximum firmware\nversion that this application version can build.\n\nIntroduced in v0.1.12.",
      "type": "array",
      "default": [
        {
          "app_version": {
            "major": 0,
            "minor": 1,
            "patch": 12
          },
          "max_buildable_firmware_version": {
            "build": 0,
            "major": 0,
            "minor": 6,
            "patch": 4
          }
        }
      ],
      "items": {
        "$ref": "#/$defs/FirmwareBuildCompatibility"
      }
    },
    "latest_app_version": {
      "description": "Latest application version available",
      "type": "string",
      "default": "0.1.16"
    },
    "link_urls": {
      "description": "Links used by the application within the UI",
      "$ref": "#/$defs/LinkUrls",
      "default": {
        "app_update": "https://onerom.org/studio/#downloads",
        "github_issue": "https://github.com/piersfinlayson/one-rom/issues",
        "linux_udev": "https://onerom.org/web/#linux",
        "one_rom": "https://onerom.org",
        "piers_rocks": "https://piers.rocks",
        "rom_configs": "https://images.onerom.org/#rom-configs",
        "win_usb": "https://onerom.org/web/#windows",
        "zadig": "https://zadig.akeo.ie/"
      }
    },
    "manifest_urls": {
      "description": "Manifests used by the application",
      "$ref": "#/$defs/ManifestUrls",
      "default": {
        "app_release": "https://images.onerom.org/studio/releases.json",
        "fw_release": "https://images.onerom.org/releases.json",
        "plugin": "https://images.onerom.org/plugins/plugins.json",
        "rom_config": "https://images.onerom.org/configs.json"
      }
    },
    "paths": {
      "description": "URL paths",
      "$ref": "#/$defs/PathUrls",
      "default": {
        "firmware_releases": "https://images.onerom.org/",
        "rom_configs": "https://images.onerom.org/"
      }
    },
    "revision": {
      "description": "Manifest revision - should be incremented whenever ANY content changes",
      "type": "integer",
      "format": "uint32",
      "default": 1,
      "minimum": 0
    },
    "schema_urls": {
      "description": "Schemas used by the application",
      "$ref": "#/$defs/Schemas",
      "default": {
        "app_manifest": "https://images.onerom.org/studio/app-schema.json",
        "app_release": "",
        "fw_release": "",
        "plugin": "https://images.onerom.org/plugins/plugin-schema.json",
        "plugin_release": "https://images.onerom.org/plugins/plugin-release-schema.json",
        "rom_config": "https://images.onerom.org/configs/schema.json"
      }
    },
    "version": {
      "description": "Manifest version - should be incremented on any breaking changes",
      "type": "integer",
      "format": "uint32",
      "default": 1,
      "minimum": 0
    }
  },
  "$defs": {
    "FirmwareBuildCompatibility": {
      "description": "Firmware build compatibility information",
      "type": "object",
      "properties": {
        "app_version": {
          "description": "App version (semver)",
          "$ref": "#/$defs/Version",
          "default": {
            "major": 0,
            "minor": 1,
            "patch": 16
          }
        },
        "max_buildable_firmware_version": {
          "description": "Maximum firmware version this app can build (not flash - any version can be flashed)",
          "$ref": "#/$defs/FirmwareVersion",
          "default": {
            "build": 0,
            "major": 0,
            "minor": 6,
            "patch": 999
          }
        }
      }
    },
    "FirmwareVersion": {
      "description": "Represents a One ROM Firmware Version",
      "type": "object",
      "properties": {
        "build": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        },
        "major": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        },
        "minor": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        },
        "patch": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        }
      },
      "required": [
        "major",
        "minor",
        "patch",
        "build"
      ]
    },
    "LinkUrls": {
      "description": "Links used within the application",
      "type": "object",
      "properties": {
        "app_update": {
          "description": "Application update page",
          "type": "string",
          "default": "https://onerom.org/studio/#downloads"
        },
        "github_issue": {
          "description": "One ROM Studio GitHub issues page",
          "type": "string",
          "default": "https://github.com/piersfinlayson/one-rom/issues"
        },
        "linux_udev": {
          "description": "Linux udev rules instructions",
          "type": "string",
          "default": "https://onerom.org/web/#linux"
        },
        "one_rom": {
          "description": "Main One ROM website",
          "type": "string",
          "default": "https://onerom.org"
        },
        "piers_rocks": {
          "description": "Main piers.rocks website",
          "type": "string",
          "default": "https://piers.rocks"
        },
        "rom_configs": {
          "description": "ROM configuration information page",
          "type": "string",
          "default": "https://images.onerom.org/#rom-configs"
        },
        "win_usb": {
          "description": "Windows USB driver instructions",
          "type": "string",
          "default": "https://onerom.org/web/#windows"
        },
        "zadig": {
          "description": "Main Zadig website",
          "type": "string",
          "default": "https://zadig.akeo.ie/"
        }
      }
    },
    "ManifestUrls": {
      "description": "Manifests used by the application",
      "type": "object",
      "properties": {
        "app_release": {
          "description": "One ROM Studio app releases manifest",
          "type": "string",
          "default": "https://images.onerom.org/studio/releases.json"
        },
        "fw_release": {
          "description": "One ROM firmware releases manifest",
          "type": "string",
          "default": "https://images.onerom.org/releases.json"
        },
        "plugin": {
          "description": "Plugin manifest",
          "type": "string",
          "default": "https://images.onerom.org/plugins/plugins.json"
        },
        "rom_config": {
          "description": "ROM configurations manifest",
          "type": "string",
          "default": "https://images.onerom.org/configs.json"
        }
      }
    },
    "PathUrls": {
      "description": "URL paths used within the application",
      "type": "object",
      "properties": {
        "firmware_releases": {
          "description": "Path to firmware releases on the server",
          "type": "string",
          "default": "https://images.onerom.org/"
        },
        "rom_configs": {
          "description": "Path to rom configs on the server",
          "type": "string",
          "default": "https://images.onerom.org/"
        }
      }
    },
    "Schemas": {
      "description": "Schemas used within the application",
      "type": "object",
      "properties": {
        "app_manifest": {
          "description": "JSON schema for the application manifest (this schema)",
          "type": "string",
          "default": "https://images.onerom.org/studio/app-schema.json"
        },
        "app_release": {
          "description": "JSON schema for application release manifest",
          "type": "string",
          "default": ""
        },
        "fw_release": {
          "description": "JSON schema for firmware release manifest",
          "type": "string",
          "default": ""
        },
        "plugin": {
          "description": "JSON schema for plugin manifest",
          "type": "string",
          "default": "https://images.onerom.org/plugins/plugin-schema.json"
        },
        "plugin_release": {
          "description": "JSON schema for plugin release manifest",
          "type": "string",
          "default": "https://images.onerom.org/plugins/plugin-release-schema.json"
        },
        "rom_config": {
          "description": "JSON schema for ROM configuration files",
          "type": "string",
          "default": "https://images.onerom.org/configs/schema.json"
        }
      }
    },
    "Version": {
      "description": "Studio version information",
      "type": "object",
      "properties": {
        "major": {
          "type": "integer",
          "format": "uint16",
          "default": 0,
          "maximum": 65535,
          "minimum": 0
        },
        "minor": {
          "type": "integer",
          "format": "uint16",
          "default": 1,
          "maximum": 65535,
          "minimum": 0
        },
        "patch": {
          "type": "integer",
          "format": "uint16",
          "default": 16,
          "maximum": 65535,
          "minimum": 0
        }
      }
    }
  }
}

=== Odie8683/one-rom/rust/studio/manifest/sample-studio.json
{
  "version": 1,
  "revision": 1,
  "latest_app_version": "0.1.16",
  "link_urls": {
    "one_rom": "https://onerom.org",
    "piers_rocks": "https://piers.rocks",
    "zadig": "https://zadig.akeo.ie/",
    "win_usb": "https://onerom.org/web/#windows",
    "github_issue": "https://github.com/piersfinlayson/one-rom/issues",
    "linux_udev": "https://onerom.org/web/#linux",
    "rom_configs": "https://images.onerom.org/#rom-configs",
    "app_update": "https://onerom.org/studio/#downloads"
  },
  "manifest_urls": {
    "fw_release": "https://images.onerom.org/releases.json",
    "rom_config": "https://images.onerom.org/configs.json",
    "app_release": "https://images.onerom.org/studio/releases.json",
    "plugin": "https://images.onerom.org/plugins/plugins.json"
  },
  "schema_urls": {
    "app_manifest": "https://images.onerom.org/studio/app-schema.json",
    "rom_config": "https://images.onerom.org/configs/schema.json",
    "fw_release": "",
    "app_release": "",
    "plugin": "https://images.onerom.org/plugins/plugin-schema.json",
    "plugin_release": "https://images.onerom.org/plugins/plugin-release-schema.json"
  },
  "paths": {
    "firmware_releases": "https://images.onerom.org/",
    "rom_configs": "https://images.onerom.org/"
  },
  "firmware_build_compatibility": [
    {
      "app_version": {
        "major": 0,
        "minor": 1,
        "patch": 12
      },
      "max_buildable_firmware_version": {
        "major": 0,
        "minor": 6,
        "patch": 4,
        "build": 0
      }
    }
  ]
}
